### ISSUE TITLE
login to containers?

### ISSUE THREAD

**Issue by dcsan** [ageapps/docker-node-mongo#1]
hi - just getting started with Docker and tried your image.

I wanted to login to the container and see what was happening, 

sudo docker exec -it 221 /bin/bash
sudo docker attach 221

however both of these ask me for a password. 
I can't see any unix users get setup as part of the scripts, can you give me some advice how to use your configuration for this?

**Comment by ageapps** [comment]
If you check the [stup script](https://github.com/ageapps/docker-node-mongo/blob/master/auth-mongo/setUpUsers.sh)  on the mongo-auth there is the user created using the environment variables. These variables are passed in de [docker-compose](https://github.com/ageapps/docker-node-mongo/blob/master/docker-compose.auth.yml)

**Comment by dcsan** [comment]
thanks for replying!
